#!/bin/bash
# Simulated output for VHS demo - called with a step number
case "$1" in
  1) # Install
    echo ""
    echo "   Installing Koda..."
    echo "   OS: darwin  Arch: arm64"
    echo ""
    echo "   Version: v0.4.28"
    echo "   Installed: ~/.local/bin/koda"
    echo "   ✓ koda v0.4.28"
    echo ""
    ;;
  2) # Setup
    echo "🔍 Checking dependencies..."
    echo ""
    echo "  ✓ kiro-cli       2.2.1"
    echo "  ✓ node           v20.19.5"
    echo "  ✓ git            2.44.0"
    echo "  ✓ gh             2.62.0"
    echo ""
    echo "✅ All dependencies installed"
    echo ""
    echo "📦 Companion tools:"
    echo "  ✓ yax"
    echo "  ✓ prompt-scorer"
    echo ""
    ;;
  3) # Doctor
    echo "  ✓ kiro-cli        2.2.1 (/usr/local/bin/kiro-cli)"
    echo "  ✓ steer-runtime   v0.2.106 (synced)"
    echo "  ✓ mcp.json        10 servers configured"
    echo "  ✓ yax             running (142 observations)"
    echo "  ✓ prompt-scorer   installed"
    echo ""
    echo "✅ All checks passed"
    echo ""
    ;;
  4) # Install profiles
    echo "📦 Installing profiles: dev-core, dev-web, dev-mobile, qa"
    echo ""
    echo "  ✓ dev-core (21 agents)"
    echo "  ✓ dev-web (5 agents)"
    echo "  ✓ dev-mobile (3 agents)"
    echo "  ✓ qa (16 agents)"
    echo ""
    echo "✅ 4 profiles installed — 45 agents available"
    echo ""
    ;;
  5) # Koda TUI + workspace
    echo ""
    echo "╔══════════════════════════════════════════════════════╗"
    echo "║  Koda v0.4.28                                        ║"
    echo "║                                                      ║"
    echo "║  Workspace: (none)          Profiles: dev-core, qa   ║"
    echo "║  Agents: 45                 MCP: 10 servers          ║"
    echo "║                                                      ║"
    echo "║  [w] Workspaces   [p] Profiles   [t] Tokens          ║"
    echo "║  [m] MCP          [e] Env vars   [enter] Chat        ║"
    echo "╚══════════════════════════════════════════════════════╝"
    echo ""
    echo "  Pressing [w]..."
    echo ""
    echo "  Select workspace:"
    echo "  ❯ app-team/app-payment-controls"
    echo "    app-team/app-config-studio"
    echo "    pos-team"
    echo "    commerce-ticketing"
    echo "    sustainment/sustainment-beast"
    echo ""
    echo "  ✅ Workspace: app-payment-controls (DPAY)"
    echo ""
    ;;
  6) # Tokens
    echo ""
    echo "━━━ Token Configuration ━━━"
    echo ""
    echo "  Jira PAT (myjira.disney.com)"
    echo "  Token: ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●"
    echo "  ✓ Saved"
    echo ""
    echo "  GitHub PAT (github.disney.com)"
    echo "  Token: ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●"
    echo "  ✓ Saved"
    echo ""
    echo "  Confluence PAT (mywiki.disney.com)"
    echo "  Token: ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●"
    echo "  ✓ Saved"
    echo ""
    echo "✅ 3 tokens configured — MCP servers regenerated"
    echo ""
    ;;
  7) # Chat - agent ready
    echo ""
    echo "👋 Ready to orchestrate your development workflow!"
    echo ""
    echo "I can help you:"
    echo "  • Implement Jira stories: \"Help me implement DPAY-1234\""
    echo "  • Coordinate multi-repo features across backend, webapi, ui"
    echo "  • Run full SDLC: story → plan → implement → review → PR"
    echo ""
    ;;
  8) # Chat - response
    echo ""
    echo "📋 Analyzing DPAY-15393..."
    echo "   Fetching story from myjira.disney.com..."
    echo "   Exploring codebase for relevant files..."
    echo ""
    echo "## Implementation Plan"
    echo ""
    echo "1. Update filterData.decorator.ts — fix startDate/startTime mismatch"
    echo "2. Add unit tests for date filter edge cases"
    echo "3. Create PR: fix/DPAY-15393-date-filter-mismatch"
    echo ""
    echo "Shall I proceed with the implementation?"
    echo ""
    ;;
esac
