bapp_id: "BAPP0060616"
app_name: "lexicon-ui"
full_name: "Lexicon UI"
description: >
  Lexicon UI web application. Internal tool for Disney Digital Producers to create, edit
  and delete Stand Alone Tickets in the product catalog.
  Keywords: lexicon admin UI, product management, ticket catalog editor.
support_studio: "Studio Control"
escalation_channel: "https://teams.microsoft.com/l/channel/19%3AN7ofY17C8fye-1cs5yLhUrSLaWsp4ggdGhUEBA24bIM1%40thread.tacv2/DX%20-%20Studio%20Control"
escalation_contacts:
  - name: "Victor Ramirez"
    role: "primary"
    contact: "Victor.Ramirez.-ND@disney.com"
servicenow:
  configuration_items:
    - "Lexicon UI - AWS Latest"
    - "Lexicon UI - AWS Load Test"
    - "Lexicon UI - AWS Production"
    - "Lexicon UI - AWS Stage"
  assignment_group: "web-global-salestickets"
documentation:
  runbook: "https://confluence.disney.com/display/WDPROS/Lexicon+UI+App+-+Runbook"
  sonar: "https://sonar.cicd.wdprapps.disney.com/dashboard?id=lexicon-ui"
docs:
  troubleshooting: "troubleshooting.md"
  business_rules: "business-rules.md"
  runbook: "runbook.md"
components:
  - component_name: "lexicon-ui"
    component_type: "frontend"
    description: "Lexicon UI Web Application"
    repository:
      url: "https://github.disney.com/commerce/wdpr-ecommerce-lexicon-ui"
      branch: "develop"
    cicd:
      platform: "harness"
      pipeline_url: "https://disney.harness.io/ng/account/1-wFe3qRQv2mUh1s9244Eg/all/orgs/Commerce/projects/Lexicon_UI/deployments"
    health_check:
      url: "https://lexicon.ui.wdprapps.disney.com/login"
      expected_status: 200
    splunk:
      index: "wdpr-ecommerce"
      base_spl: "index=wdpr-ecommerce ecs_cluster=\"wdpr-ecommerce-S0001323-usw2-<env>*\" ecs_task_definition=\"lexicon-ui*\""
    appdynamics:
      app_name: "prod_ecommerce-S0001323_aws"
      dashboard_url: "https://disney-prod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&application=563"
    cloud:
      provider: "AWS"
      region: "us-west-2"
      infra_type: "ECS"
      cluster_id: "wdpr-ecommerce-S0001323-usw2-<env>"
      service_name: "lexicon-ui"
    other_environments:
      latest:
        health_check:
          url: "https://latest.lexicon.ui.wdprapps.disney.com/login"
      stage:
        health_check:
          url: "https://stage.lexicon.ui.wdprapps.disney.com/login"
      load:
        health_check:
          url: "https://load.lexicon.ui.wdprapps.disney.com/login"
