bapp_id: "BAPP0242760"
app_name: "ttc-lexvas"
full_name: "WDPR TTC LexVAS"
description: >
  TTC Lexicon View Assembler Service. Provides ticket type catalog views for WDW
  specifically for 3rd party sales via the TTC platform.
  Keywords: ttc, lexvas, ticket type catalog, 3rd party sales, product catalog.
support_studio: "Studio Control"
escalation_channel: "https://teams.microsoft.com/l/channel/19%3AN7ofY17C8fye-1cs5yLhUrSLaWsp4ggdGhUEBA24bIM1%40thread.tacv2/DX%20-%20Studio%20Control"
escalation_contacts:
  - name: "Victor Ramirez"
    role: "primary"
    contact: "Victor.Ramirez.-ND@disney.com"
servicenow:
  configuration_items:
    - "WDPR TTC LexVAS WDW - AWS Latest"
    - "WDPR TTC LexVAS WDW - AWS Load Test"
    - "WDPR TTC LexVAS WDW - AWS Production"
    - "WDPR TTC LexVAS WDW - AWS Stage"
  assignment_group: "web-global-salestickets"
documentation:
  runbook: "https://confluence.disney.com/display/WDPROS/TTC+LexVAS+WDW+-+Runbook"
  swagger: "https://latest.ttc-lexvas-wdw.wdprapps.disney.com/ttc-lexvas/docs/index.html"
  sonar: "https://sonar.cicd.wdprapps.disney.com/dashboard?id=com.disney.wdpro.service%3Attc-lexvas"
docs:
  troubleshooting: "troubleshooting.md"
  business_rules: "business-rules.md"
  runbook: "runbook.md"
components:
  - component_name: "ttc-lexvas"
    component_type: "api"
    description: "TTC LexVAS API"
    repository:
      url: "https://github.disney.com/commerce/wdpr-ecommerce-ttc-lexvas"
      branch: "develop"
    cicd:
      platform: "harness"
      pipeline_url: "https://disney.harness.io/ng/account/1-wFe3qRQv2mUh1s9244Eg/all/orgs/Commerce/projects/WDPR_TTC_LexVAS/deployments"
    health_check:
      url: "https://ttc-lexvas-wdw.wdprapps.disney.com/ttc-lexvas/health/deep"
      expected_status: 200
    splunk:
      index: "wdpr-ecommerce"
      base_spl: "index=wdpr-ecommerce ecs_cluster=\"wdpr-ecommerce-S0001663-use1-<env>*\" ecs_task_definition=\"ttc-lexvas*\""
      dashboards:
        metrics: "https://splunk.wdprapps.disney.com/en-US/app/launcher/studio_control__ttc_lexvas"
        metrics_preprod: "https://stage.splunk.wdprapps.disney.com/en-US/app/search/studio_control__ttc_lexvas"
        cache: "https://stage.splunk.wdprapps.disney.com/en-US/app/search/studio_control__ttc_lexvas__new_cache"
    appdynamics:
      dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_DASHBOARD"
    cloud:
      provider: "AWS"
      region: "us-east-1"
      infra_type: "ECS"
      cluster_id: "wdpr-ecommerce-S0001663-use1-<env>"
      service_name: "ttc-lexvas"
    other_environments:
      latest:
        health_check:
          url: "https://latest.ttc-lexvas-wdw.wdprapps.disney.com/ttc-lexvas/health/deep"
      stage:
        health_check:
          url: "https://stage.ttc-lexvas-wdw.wdprapps.disney.com/ttc-lexvas/health/deep"
      load:
        health_check:
          url: "https://load.ttc-lexvas-wdw.wdprapps.disney.com/ttc-lexvas/health/deep"
