bapp_id: "BAPP0081809"
app_name: "tms-dlr"
full_name: "Ticket Management Service (DLR)"
description: "Internal and external ticket management for DLR"
support_studio: "Studio Kaos"
escalation_channel: "https://teams.microsoft.com/l/channel/19%3AeNbcha4UraJUCngdy1oP_SuMd5GrCvgScaei1uhdhoc1%40thread.tacv2/DX%20-%20Studio%20Kaos?groupId=35a13470-e675-44b7-810e-f062466cffb5&tenantId=56b731a8-a2ac-4c32-bf6b-616810e913c6&ngc=true&allowXTenantAccess=true"
escalation_contacts:
  - name: "Gabriela Rossi"
    role: "primary"
    contact: "Gabriela.X.Rossi.-ND@disney.com"
servicenow:
  configuration_item: "WDPRD Ticket Management Service"
  assignment_group: "web-global-salestickets"
documentation:
  runbook: "https://confluence.disney.com/spaces/WDPROS/pages/484022646/TMS"
  wiki: "https://confluence.disney.com/spaces/WDPROS/pages/484022646/TMS"
  architecture_diagram: "https://docs.google.com/spreadsheets/d/1lx97wsiUTiLX30szpyFzPBC7twwLR2G0S48YQ3JfMeo/edit#gid=0"
docs:
  troubleshooting: "troubleshooting.md"
  business_rules: "business-rules.md"
  runbook: "runbook.md"
components:
  - component_name: "tms-dlr-int"
    component_type: "api"
    description: "Internal services (Profile, GSS, Keyring, VQ)"
    health_check:
      url: "https://tms.int.dlr.wdpro.disney.com/ticket-management-service/health/deep"
      expected_status: 200
    splunk:
      index: "wdpr-ecommerce"
      base_spl: "index=wdpr-ecommerce ecs_cluster=\"dlr-ecommerce-S0001477-usw2*\" ecs_task_definition=\"tmsint-svc*\""
      error_spl: "index=wdpr-ecommerce ecs_cluster=\"dlr-ecommerce-S0001477-usw2*\" ecs_task_definition=\"tmsint-svc*\" (\"*error*\" OR \"*exception*\")"
      latency_spl: "index=wdpr-ecommerce ecs_cluster=\"dlr-ecommerce-S0001477-usw2*\" ecs_task_definition=\"tmsint-svc*\" response-millis | rex \"response-millis=(?<response_millis>\\d+)\" | stats avg(response_millis) as avg_ms, p95(response_millis) as p95_ms"
    appdynamics:
      app_name: "prod_ecommerce-S0001477_aws"
      app_id: "501"
      tier: "core_ecommerce-S0001477_tmsint-svc-dlr"
      dashboard_url: "https://disney-prod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=501&component=306250&dashboardMode=force"
    grafana:
      dashboard_url: "https://sid.disney.com/grafana/d/6cRDMP8nz/atlas-observability-metrics-ecs?orgId=1&var-Environment=prod&var-Account=wdpr-ecommerce-prod&var-Region=us-west-2&var-clusters=dlr-ecommerce-S0001477-usw2-prd&var-service=tmsint-svc-prod-live"
    cloud:
      provider: "AWS"
      region: "us-west-2"
      account_id: "820987038150"
      infra_type: "ECS"
      cluster_id: "dlr-ecommerce-S0001477-usw2-prd"
      service_name: "tmsint-svc-prod-live"
  - component_name: "tms-dlr-ext"
    component_type: "api"
    description: "Guest-facing traffic (Itinerary, CME, TnP, MK Renewals)"
    health_check:
      url: "https://tms.dlr.wdpro.disney.com/ticket-management-service/health/deep"
      expected_status: 200
    splunk:
      index: "wdpr-ecommerce"
      base_spl: "index=wdpr-ecommerce ecs_cluster=\"dlr-ecommerce-S0001477-usw2*\" ecs_task_definition=\"tms-service-svc*\""
      error_spl: "index=wdpr-ecommerce ecs_cluster=\"dlr-ecommerce-S0001477-usw2*\" ecs_task_definition=\"tms-service-svc*\" (\"*error*\" OR \"*exception*\")"
      latency_spl: "index=wdpr-ecommerce ecs_cluster=\"dlr-ecommerce-S0001477-usw2*\" ecs_task_definition=\"tms-service-svc*\" response-millis | rex \"response-millis=(?<response_millis>\\d+)\" | stats avg(response_millis) as avg_ms, p95(response_millis) as p95_ms"
    appdynamics:
      app_name: "prod_ecommerce-S0001477_aws"
      app_id: "501"
      tier: "core_ecommerce-S0001477_tms_service_svc_dlr"
      dashboard_url: "https://disney-prod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=501&component=366252&dashboardMode=force"
    grafana:
      dashboard_url: "https://sid.disney.com/grafana/d/6cRDMP8nz/atlas-observability-metrics-ecs?orgId=1&var-Environment=prod&var-Account=wdpr-ecommerce-prod&var-Region=us-west-2&var-clusters=dlr-ecommerce-S0001477-usw2-prd&var-service=tms-service-svc-prod-live"
    cloud:
      provider: "AWS"
      region: "us-west-2"
      account_id: "820987038150"
      infra_type: "ECS"
      cluster_id: "dlr-ecommerce-S0001477-usw2-prd"
      service_name: "tms-service-svc-prod-live"
