bapp_id: "BAPP0081809"
app_name: "tms-wdw"
full_name: "Ticket Management Service (WDW)"
description: >
  Digital services for post-purchase and park operation flows for WDW. Provides endpoints for mobile and web flows
  to retrieve guest entitlements. Completely relies on GAM for entitlement retrieval.
  Flows: ticket-linking, ticket-upgrade-wdw.
  Keywords: ticket not showing, can't see ticket, link ticket, claim ticket, LLMP not showing, ticket visibility,
  shared ticket, self admit, MEP, WDW AP upgrade, upgrade annual pass, WDW ticket upgrade, GAM, TMS.
support_studio: "Studio Control"
escalation_channel: "https://teams.microsoft.com/l/channel/19%3AN7ofY17C8fye-1cs5yLhUrSLaWsp4ggdGhUEBA24bIM1%40thread.tacv2/DX%20-%20Studio%20Control?groupId=35a13470-e675-44b7-810e-f062466cffb5&tenantId=56b731a8-a2ac-4c32-bf6b-616810e913c6&ngc=true&allowXTenantAccess=true"
escalation_contacts:
  - name: "Victor Ramirez"
    role: "primary"
    contact: "Victor.Ramirez.-ND@disney.com"
servicenow:
  configuration_item: "WDPRD Ticket Management Service"
  assignment_group: "web-global-salestickets"
documentation:
  runbook: "https://confluence.disney.com/spaces/WDPROS/pages/681701804/WDW+TMS+Runbook"
  wiki: "https://confluence.disney.com/spaces/WDPROS/pages/484022646/TMS"
  architecture_diagram: "https://docs.google.com/spreadsheets/d/1lx97wsiUTiLX30szpyFzPBC7twwLR2G0S48YQ3JfMeo/edit#gid=0"
docs:
  troubleshooting: "troubleshooting.md"
  business_rules: "business-rules.md"
  runbook: "runbook.md"
components:
  - component_name: "tms-wdw-int"
    component_type: "api"
    description: "Internal services for WDW (Profile, GSS, Keyring)"
    repository:
      url: "https://github.disney.com/commerce/wdpr-ecommerce-tms-svc"
      branch: "develop"
    cicd:
      platform: "harness"
      pipeline_url: "https://disney.harness.io/ng/account/1-wFe3qRQv2mUh1s9244Eg/all/orgs/Commerce/projects/WDPRD_Ticket_Management_Service/deployments"
    health_check:
      url: "https://tms.int.wdw.wdpro.disney.com/ticket-management-service/health/deep"
      expected_status: 200
    splunk:
      index: "wdpr-ecommerce"
      base_spl: "index=wdpr-ecommerce ecs_cluster=\"wdw-ecommerce-S0001479-usw2*\" ecs_task_definition=\"tmsint-svc*\""
      error_spl: "index=wdpr-ecommerce ecs_cluster=\"wdw-ecommerce-S0001479-usw2*\" ecs_task_definition=\"tmsint-svc*\" (\"*error*\" OR \"*exception*\")"
      latency_spl: "index=wdpr-ecommerce ecs_cluster=\"wdw-ecommerce-S0001479-usw2*\" ecs_task_definition=\"tmsint-svc*\" response-millis | rex \"response-millis=(?<response_millis>\\d+)\" | stats avg(response_millis) as avg_ms, p95(response_millis) as p95_ms"
    appdynamics:
      app_name: "prod_ecommerce-S0001479_aws"
      app_id: "563"
      tier: "core_ecommerce-S0001479_tmsint-wdw-svc"
      dashboard_url: "https://disney-prod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=563&component=288251&dashboardMode=force"
    grafana:
      dashboard_url: "https://sid.disney.com/grafana/d/6cRDMP8nz/atlas-observability-metrics-ecs?orgId=1&var-Environment=prod&var-Account=wdpr-ecommerce-prod&var-Region=us-west-2&var-clusters=wdw-ecommerce-S0001479-usw2-prd&var-service=tmsint-wdw-svc-prod-live"
    cloud:
      provider: "AWS"
      region: "us-west-2"
      account_id: "820987038150"
      infra_type: "ECS"
      cluster_id: "wdw-ecommerce-S0001479-usw2-prd"
      service_name: "tmsint-wdw-svc-prod-live"
      services:
        - type: "rds"
          name: "wdw-tms-prod-mysql.czadbdnytwxi.us-west-2.rds.amazonaws.com:3306/wdwtms_prod"
        - type: "elasticache"
          name: "wdw-tms-prod-ec.i8pkwr.0001.usw2.cache.amazonaws.com"
    other_environments:
      stage:
        health_check:
          url: "https://stage.tms.int.wdw.wdpro.disney.com/ticket-management-service/health/deep"
        appdynamics:
          app_id: "3056"
          dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=3056&component=6401643&dashboardMode=force"
        cloud:
          cluster_id: "wdw-ecommerce-S0001479-usw2-stg"
          service_name: "tmsint-wdw-svc-stage-live"
          services:
            - type: "rds"
              name: "wdw-tms-svc-stage-master.wdatdbs.disney.com:4001/wdwtms_stage"
            - type: "elasticache"
              name: "wdw-tms-stage-ec.i8pkwr.0001.usw2.cache.amazonaws.com"
      load:
        health_check:
          url: "https://lt.tms.int.wdw.wdpro.disney.com/ticket-management-service/health/deep"
        appdynamics:
          app_id: "3058"
          dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=3058&component=6401747&dashboardMode=force"
        cloud:
          cluster_id: "wdw-ecommerce-S0001479-usw2-lod"
          service_name: "tmsint-wdw-svc-load-live"
          services:
            - type: "rds"
              name: "wdw-tms-svc-load-master.wdatdbs.disney.com:4001/wdwtms_lt"
            - type: "elasticache"
              name: "wdw-tms-lt-ec.i8pkwr.0001.usw2.cache.amazonaws.com"
      latest:
        health_check:
          url: "https://latest.tms.int.wdw.wdpro.disney.com/ticket-management-service/health/deep"
        appdynamics:
          app_id: "2846"
          dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=2846&component=6394101&dashboardMode=force"
        cloud:
          cluster_id: "wdw-ecommerce-S0001479-usw2-lst"
          service_name: "tmsint-wdw-svc-latest-live"
          services:
            - type: "rds"
              name: "wdw-tms-svc-1-mariadb-latest.che79lwtdc3w.us-west-2.rds.amazonaws.com:4001/wdwtms_latest"
            - type: "elasticache"
              name: "wdwtms-latest.7ozysg.clustercfg.usw2.cache.amazonaws.com"

  - component_name: "tms-wdw-ext"
    component_type: "api"
    description: "Guest-facing traffic for WDW (Itinerary, CME, Mobile App)"
    repository:
      url: "https://github.disney.com/commerce/wdpr-ecommerce-tms-svc"
      branch: "develop"
    cicd:
      platform: "harness"
      pipeline_url: "https://disney.harness.io/ng/account/1-wFe3qRQv2mUh1s9244Eg/all/orgs/Commerce/projects/WDPRD_Ticket_Management_Service/deployments"
    health_check:
      url: "https://tms.wdw.wdpro.disney.com/ticket-management-service/health/deep"
      expected_status: 200
    splunk:
      index: "wdpr-ecommerce"
      base_spl: "index=wdpr-ecommerce ecs_cluster=\"wdw-ecommerce-S0001479-usw2*\" ecs_task_definition=\"tms-svc*\""
      error_spl: "index=wdpr-ecommerce ecs_cluster=\"wdw-ecommerce-S0001479-usw2*\" ecs_task_definition=\"tms-svc*\" (\"*error*\" OR \"*exception*\")"
      latency_spl: "index=wdpr-ecommerce ecs_cluster=\"wdw-ecommerce-S0001479-usw2*\" ecs_task_definition=\"tms-svc*\" response-millis | rex \"response-millis=(?<response_millis>\\d+)\" | stats avg(response_millis) as avg_ms, p95(response_millis) as p95_ms"
    appdynamics:
      app_name: "prod_ecommerce-S0001479_aws"
      app_id: "563"
      tier: "core_ecommerce-S0001479_tms-wdw-svc"
      dashboard_url: "https://disney-prod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=563&component=288169&dashboardMode=force"
    grafana:
      dashboard_url: "https://sid.disney.com/grafana/d/6cRDMP8nz/atlas-observability-metrics-ecs?orgId=1&var-Environment=prod&var-Account=wdpr-ecommerce-prod&var-Region=us-west-2&var-clusters=wdw-ecommerce-S0001479-usw2-prd&var-service=tms-wdw-svc-prod-live"
    cloud:
      provider: "AWS"
      region: "us-west-2"
      account_id: "820987038150"
      infra_type: "ECS"
      cluster_id: "wdw-ecommerce-S0001479-usw2-prd"
      service_name: "tms-wdw-svc-prod-live"
      services:
        - type: "rds"
          name: "wdw-tms-prod-mysql.czadbdnytwxi.us-west-2.rds.amazonaws.com:3306/wdwtms_prod"
        - type: "elasticache"
          name: "wdw-tms-prod-ec.i8pkwr.0001.usw2.cache.amazonaws.com"
    other_environments:
      stage:
        health_check:
          url: "https://stage.tms.wdw.wdpro.disney.com/ticket-management-service/health/deep"
        appdynamics:
          app_id: "3056"
          dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=3056&component=6401644&dashboardMode=force"
        cloud:
          cluster_id: "wdw-ecommerce-S0001479-usw2-stg"
          service_name: "tms-wdw-svc-stage-live"
      load:
        health_check:
          url: "https://lt.tms.wdw.wdpro.disney.com/ticket-management-service/health/deep"
        appdynamics:
          app_id: "3058"
          dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=3058&component=6401747&dashboardMode=force"
        cloud:
          cluster_id: "wdw-ecommerce-S0001479-usw2-lod"
          service_name: "tms-wdw-svc-load-live"
      latest:
        health_check:
          url: "https://latest.tms.wdw.wdpro.disney.com/ticket-management-service/health/deep"
        appdynamics:
          app_id: "2846"
          dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60&application=2846&component=6394100&dashboardMode=force"
        cloud:
          cluster_id: "wdw-ecommerce-S0001479-usw2-lst"
          service_name: "tms-wdw-svc-latest-live"
