bapp_id: "BAPP0247964"
app_name: "tpac"
full_name: "WDW Tickets Price Avail Cache Service"
description: >
  Tickets Price Availability Cache Service. Caches pricing and availability data for WDW tickets.
  Keywords: TPAC, price cache, availability cache, ticket pricing, price-avail.
support_studio: "Studio Control"
escalation_channel: "https://teams.microsoft.com/l/channel/19%3AN7ofY17C8fye-1cs5yLhUrSLaWsp4ggdGhUEBA24bIM1%40thread.tacv2/DX%20-%20Studio%20Control"
escalation_contacts:
  - name: "Victor Ramirez"
    role: "primary"
    contact: "Victor.Ramirez.-ND@disney.com"
servicenow:
  configuration_items:
    - "WDW Tickets Price Avail Cache Service - AWS Latest"
    - "WDW Tickets Price Avail Cache Service - AWS Load Test"
    - "WDW Tickets Price Avail Cache Service - AWS Production"
    - "WDW Tickets Price Avail Cache Service - AWS Stage"
  assignment_group: "web-global-salestickets"
documentation:
  runbook: "https://confluence.disney.com/spaces/WDPROS/pages/1860708661/TPAC+WDW+-+Runbook"
  swagger: "https://latest.tpac-svc-wdw.wdprapps.disney.com/price-avail/api/api-docs?url=/price-avail/api/openapi.json"
  sonar: "https://sonar.cicd.wdprapps.disney.com/portfolio?id=Scott-DePriest_Service_New"
docs:
  troubleshooting: "troubleshooting.md"
  business_rules: "business-rules.md"
  runbook: "runbook.md"
components:
  - component_name: "tpac-svc"
    component_type: "api"
    description: "TPAC Service"
    repository:
      url: "https://github.disney.com/commerce/wdpr-ecommerce-tpac-svc"
      branch: "develop"
    cicd:
      platform: "harness"
      pipeline_url: "https://disney.harness.io/ng/account/1-wFe3qRQv2mUh1s9244Eg/all/orgs/Commerce/projects/WDW_Tickets_Price_Avail_Cache_Service/deployments"
    health_check:
      url: "https://tpac-svc-wdw.wdprapps.disney.com/price-avail/api/health"
      expected_status: 200
    splunk:
      index: "wdpr-ecommerce"
      base_spl: "index=wdpr-ecommerce ecs_cluster=\"wdw-ecommerce-S0014492-use1-<env>\" ecs_task_definition=\"tpac-svc*\""
      prod_index: "wdw_tpac"
      prod_spl: "index=wdw_tpac source=*us-east-1*"
      dashboards:
        preprod: "https://stage.splunk.wdprapps.disney.com/en-US/app/search/tpac_-_lt"
        prod: "https://splunk.wdprapps.disney.com/en-US/app/wdpr_payments/tpac_-_prod"
    appdynamics:
      dashboard_url: "https://disney-preprod.saas.appdynamics.com/controller/#/location=APP_COMPONENT_MANAGER"
    cloud:
      provider: "AWS"
      region: "us-east-1"
      infra_type: "ECS"
      cluster_id: "wdw-ecommerce-S0014492-use1-<env>"
      service_name: "tpac-svc"
    other_environments:
      latest:
        health_check:
          url: "https://latest.tpac-svc-wdw.wdprapps.disney.com/price-avail/api/health"
      stage:
        health_check:
          url: "https://stage.tpac-svc-wdw.wdprapps.disney.com/price-avail/api/health"
      load:
        health_check:
          url: "https://load.tpac-svc-wdw.wdprapps.disney.com/price-avail/api/health"
