#!/bin/bash
# Install/manage the weekly ticketing sprint report launchd job
# Part of: commerce-ticketing-team / ops profile
# Supports: macOS (launchd), Linux (cron), Windows (Task Scheduler via Git Bash)

PLIST_NAME="com.disney.weekly-ticketing-sprint-report"
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT_PATH="${SCRIPT_DIR}/scripts/generate_report.py"
CONFIG_FILE="${SCRIPT_DIR}/.report_config"

# --- Cross-platform defaults ---
detect_os() {
    case "$(uname -s)" in
        Darwin*) echo "macos" ;;
        Linux*)  echo "linux" ;;
        MINGW*|MSYS*|CYGWIN*) echo "windows" ;;
        *) echo "unknown" ;;
    esac
}

default_reports_dir() {
    local os=$(detect_os)
    case "$os" in
        macos|linux) echo "$HOME/Documents/Control-Kaos Reports/reports" ;;
        windows)     echo "$USERPROFILE/Documents/Control-Kaos Reports/reports" ;;
    esac
}

# --- Configuration ---
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        REPORTS_DIR=$(grep "^REPORTS_DIR=" "$CONFIG_FILE" | cut -d\" -f2)
        JIRA_METHOD=$(grep "^JIRA_METHOD=" "$CONFIG_FILE" | cut -d\" -f2)
        JIRA_EMAIL=$(grep "^JIRA_EMAIL=" "$CONFIG_FILE" | cut -d\" -f2)
        JIRA_TOKEN=$(grep "^JIRA_TOKEN=" "$CONFIG_FILE" | cut -d\" -f2)
    fi
    REPORTS_DIR="${REPORTS_DIR:-$(default_reports_dir)}"
    JIRA_METHOD="${JIRA_METHOD:-api}"
    LOG_DIR="${REPORTS_DIR%/reports}/logs"
}

configure() {
    echo ""
    echo "  ╔══════════════════════════════════════════════╗"
    echo "  ║   Weekly Sprint Report — Configuration      ║"
    echo "  ╚══════════════════════════════════════════════╝"
    echo ""
    
    # --- Reports directory ---
    local default_dir=$(default_reports_dir)
    echo "  1. Where should reports be saved?"
    echo "     Default: ${default_dir}"
    echo ""
    read -p "     Reports directory [Enter for default]: " user_dir
    
    if [ -n "$user_dir" ]; then
        REPORTS_DIR="$user_dir"
    else
        REPORTS_DIR="$default_dir"
    fi
    LOG_DIR="${REPORTS_DIR%/reports}/logs"
    mkdir -p "$REPORTS_DIR"
    mkdir -p "$LOG_DIR"
    
    # --- Jira connection method ---
    echo ""
    echo "  2. How do you connect to Jira (disneyexperiences.atlassian.net)?"
    echo ""
    echo "     [1] Atlassian API token (recommended — works everywhere)"
    echo "     [2] Docker MCP container (mcp-atlassian — if already configured)"
    echo ""
    read -p "     Choose [1/2, default=1]: " jira_choice
    
    case "${jira_choice:-1}" in
        1)
            JIRA_METHOD="api"
            echo ""
            echo "     You'll need an Atlassian API token."
            echo "     Generate one at: https://id.atlassian.com/manage-profile/security/api-tokens"
            echo ""
            read -p "     Atlassian email: " jira_email
            read -sp "     API token: " jira_token
            echo ""
            JIRA_EMAIL="$jira_email"
            JIRA_TOKEN="$jira_token"
            echo "     ✅ API credentials configured"
            ;;
        2)
            JIRA_METHOD="docker_mcp"
            JIRA_EMAIL=""
            JIRA_TOKEN=""
            echo "     ✅ Will use Docker MCP container (mcp-atlassian)"
            # Verify docker is available
            if ! docker ps --filter name=mcp-atlassian --format "{{.Names}}" 2>/dev/null | grep -q mcp-atlassian; then
                echo "     ⚠️  Warning: mcp-atlassian container not found running."
                echo "     Make sure it's running before the report generates."
            fi
            ;;
    esac
    
    # --- Save config ---
    cat > "$CONFIG_FILE" << CONF
# Weekly Ticketing Sprint Report - Configuration
# Generated by install.sh on $(date)
# This file is in .gitignore — local only
REPORTS_DIR="${REPORTS_DIR}"
JIRA_METHOD="${JIRA_METHOD}"
JIRA_EMAIL="${JIRA_EMAIL}"
JIRA_TOKEN="${JIRA_TOKEN}"
CONF
    chmod 600 "$CONFIG_FILE"  # Protect token
    
    echo ""
    echo "  ✅ Configuration saved (${CONFIG_FILE})"
    echo "     Reports: ${REPORTS_DIR}"
    echo "     Jira: ${JIRA_METHOD}"
}

# --- Platform-specific install ---
install_macos() {
    local plist_path="$HOME/Library/LaunchAgents/${PLIST_NAME}.plist"
    
    launchctl unload "$plist_path" 2>/dev/null
    
    cat > "$plist_path" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_NAME}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/python3</string>
        <string>${SCRIPT_PATH}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Weekday</key>
        <integer>1</integer>
        <key>Hour</key>
        <integer>10</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/report_gen.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/report_gen_error.log</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
PLIST
    
    launchctl load "$plist_path"
    echo "   ✅ launchd job installed (Mondays 10:00 AM)"
}

install_linux() {
    local cron_entry="0 10 * * 1 /usr/bin/python3 ${SCRIPT_PATH} >> ${LOG_DIR}/report_gen.log 2>&1"
    (crontab -l 2>/dev/null | grep -v "$SCRIPT_PATH"; echo "$cron_entry") | crontab -
    echo "   ✅ cron job installed (Mondays 10:00 AM)"
}

install_windows() {
    echo "   ⚠️  Windows: Create a Task Scheduler entry:"
    echo "   Program: python3"
    echo "   Arguments: ${SCRIPT_PATH}"
    echo "   Trigger: Weekly, Monday at 10:00 AM"
}

# --- Uninstall ---
uninstall_macos() {
    local plist_path="$HOME/Library/LaunchAgents/${PLIST_NAME}.plist"
    launchctl unload "$plist_path" 2>/dev/null
    rm -f "$plist_path"
}

uninstall_linux() {
    crontab -l 2>/dev/null | grep -v "$SCRIPT_PATH" | crontab -
}

# --- Main ---
case "${1:-install}" in
    install)
        configure
        
        echo ""
        echo "  Installing schedule..."
        case "$(detect_os)" in
            macos)   install_macos ;;
            linux)   install_linux ;;
            windows) install_windows ;;
            *)       echo "   ❌ Unsupported OS"; exit 1 ;;
        esac
        
        echo ""
        echo "  ✅ Setup complete! Run '$0 run' to test."
        ;;
    
    uninstall)
        echo "Removing weekly report schedule..."
        case "$(detect_os)" in
            macos)   uninstall_macos ;;
            linux)   uninstall_linux ;;
            windows) echo "Remove from Task Scheduler manually." ;;
        esac
        rm -f "$CONFIG_FILE"
        echo "✅ Uninstalled."
        ;;
    
    status)
        load_config
        echo "OS: $(detect_os)"
        echo "Reports: ${REPORTS_DIR}"
        echo "Jira method: ${JIRA_METHOD}"
        echo "Script: ${SCRIPT_PATH}"
        case "$(detect_os)" in
            macos)
                if launchctl list 2>/dev/null | grep -q "$PLIST_NAME"; then
                    echo "Schedule: ✅ Active (Mondays 10:00 AM)"
                else
                    echo "Schedule: ❌ Not installed"
                fi
                ;;
            linux)
                if crontab -l 2>/dev/null | grep -q "$SCRIPT_PATH"; then
                    echo "Schedule: ✅ Active (Mondays 10:00 AM)"
                else
                    echo "Schedule: ❌ Not installed"
                fi
                ;;
        esac
        ;;
    
    run)
        load_config
        echo "Running report generation now..."
        python3 "$SCRIPT_PATH"
        ;;
    
    *)
        echo "Usage: $0 {install|uninstall|status|run}"
        exit 1
        ;;
esac
